<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>MySQL Connexion Test Failed: cannot connect to local server for Data Sources</title>
    <link>https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509</link>
    <description>Dear Community,

I have installed Redash using the following link : https://gitlab.in2p3.fr/sist/tuto-instal-redash ; which enables me to connect to Redash using the following URL : http://localhost:8080/.

I am trying to use the Data Sources option in order to load MySQL databases into a dashboard. However, when I fill the form by giving the information about the host, port, and user, I face an error when testing the connection (see attached the screenshot) :

![test_redash|618x500](upload://i7DdPidwnUKX0M2WCu9xkyxlEWH.png)

I have root privileges to the MySQL server, and I can normaly connect to the database using these information through a Python script, or a Django app for instance. Also, I imagine that the problem comes from the connexion between Redash and MySQL, but I can&#39;t still solve this even by changing the host with my local ip and so on. 

Can you help me on the steps to follow please ? If it is a problem of privilzges for a user or a problem of address ?

Thank you very much in advance.</description>
    
    <lastBuildDate>Tue, 07 Feb 2023 02:01:47 +0000</lastBuildDate>
    <category>Feature Requests</category>
    <atom:link href="https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>MySQL Connexion Test Failed: cannot connect to local server for Data Sources</title>
        <dc:creator><![CDATA[zhongshaoming1]]></dc:creator>
        <description><![CDATA[
            <p>I think this is an error caused by putting ‘localhost’ in your Mysql host. localhost means 127.0.0.1 in the redash container, not the host where the redash container is deployed</p>
          <p><a href="https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509/2</link>
        <pubDate>Tue, 07 Feb 2023 02:01:47 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11509-2</guid>
        <source url="https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509.rss">MySQL Connexion Test Failed: cannot connect to local server for Data Sources</source>
      </item>
      <item>
        <title>MySQL Connexion Test Failed: cannot connect to local server for Data Sources</title>
        <dc:creator><![CDATA[marduq]]></dc:creator>
        <description><![CDATA[
            <p>Dear Community,</p>
<p>I have installed Redash using the following link : <a href="https://gitlab.in2p3.fr/sist/tuto-instal-redash" class="inline-onebox" rel="noopener nofollow ugc">sist / tuto-instal-redash · GitLab</a> ; which enables me to connect to Redash using the following URL : <a href="http://localhost:8080/" rel="noopener nofollow ugc">http://localhost:8080/</a>.</p>
<p>I am trying to use the Data Sources option in order to load MySQL databases into a dashboard. However, when I fill the form by giving the information about the host, port, and user, I face an error when testing the connection (see attached the screenshot) :</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/7/7f0401b5d71484331d308c3dff6730fae8743c7f.png" data-download-href="/uploads/short-url/i7DdPidwnUKX0M2WCu9xkyxlEWH.png?dl=1" title="test_redash" rel="noopener nofollow ugc"><img src="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7f0401b5d71484331d308c3dff6730fae8743c7f_2_618x500.png" alt="test_redash" data-base62-sha1="i7DdPidwnUKX0M2WCu9xkyxlEWH" width="618" height="500" srcset="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7f0401b5d71484331d308c3dff6730fae8743c7f_2_618x500.png, https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7f0401b5d71484331d308c3dff6730fae8743c7f_2_927x750.png 1.5x, https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/7/7f0401b5d71484331d308c3dff6730fae8743c7f.png 2x" data-dominant-color="F9FBFC"></a></div><p></p>
<p>I have root privileges to the MySQL server, and I can normaly connect to the database using these information through a Python script, or a Django app for instance. Also, I imagine that the problem comes from the connexion between Redash and MySQL, but I can’t still solve this even by changing the host with my local ip and so on.</p>
<p>Can you help me on the steps to follow please ? If it is a problem of privilzges for a user or a problem of address ?</p>
<p>Thank you very much in advance.</p>
          <p><a href="https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509/1</link>
        <pubDate>Wed, 25 Jan 2023 11:32:00 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11509-1</guid>
        <source url="https://discuss.redash.io/t/mysql-connexion-test-failed-cannot-connect-to-local-server-for-data-sources/11509.rss">MySQL Connexion Test Failed: cannot connect to local server for Data Sources</source>
      </item>
  </channel>
</rss>
