<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Unable to send invitation/password reset emails</title>
    <link>https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642</link>
    <description>Hello üëãüèª

Redash is unable to send email to invite a new user or reset its password. 
Email seems to be correctly configured as `docker-compose run --rm server manage send_test_mail &quot;bar@foo.com&quot;` is sending a test email.

In the logs of the redash server, when I&#39;m trying to reset a password (with `/forgot`), I have the following error:

```
[2022-06-17 08:11:52,452][PID:12][ERROR][redash.handlers.authentication] Failed to verify invite token: XXxXxX0XXX, org=None
Traceback (most recent call last):
  File &quot;/app/redash/handlers/authentication.py&quot;, line 31, in render_token_login_page
    user_id = validate_token(token)
  File &quot;/app/redash/authentication/account.py&quot;, line 41, in validate_token
    return serializer.loads(token, max_age=max_token_age)
  File &quot;/usr/local/lib/python2.7/site-packages/itsdangerous.py&quot;, line 643, in loads
    .unsign(s, max_age, return_timestamp=True)
  File &quot;/usr/local/lib/python2.7/site-packages/itsdangerous.py&quot;, line 436, in unsign
    raise sig_error
BadSignature: No &#39;.&#39; found in value
```

It has been working on the past and I do not remember changing the configuration. 
I&#39;m using a self-host version of Redash 8.0.0+b32245 (a16f551e), using Ubuntu 18.04.

Thank you for your help!</description>
    
    <lastBuildDate>Fri, 18 Nov 2022 11:10:18 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Unable to send invitation/password reset emails</title>
        <dc:creator><![CDATA[edouardjmn]]></dc:creator>
        <description><![CDATA[
            <p>Same issue with Redash 10.1.0 (2589bef1)</p>
          <p><a href="https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642/2</link>
        <pubDate>Fri, 18 Nov 2022 11:10:18 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10642-2</guid>
        <source url="https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642.rss">Unable to send invitation/password reset emails</source>
      </item>
      <item>
        <title>Unable to send invitation/password reset emails</title>
        <dc:creator><![CDATA[edouardjmn]]></dc:creator>
        <description><![CDATA[
            <p>Hello <img src="https://emoji.discourse-cdn.com/twitter/wave/2.png?v=12" title=":wave:t2:" class="emoji" alt=":wave:t2:" loading="lazy" width="20" height="20"></p>
<p>Redash is unable to send email to invite a new user or reset its password.<br>
Email seems to be correctly configured as <code>docker-compose run --rm server manage send_test_mail "bar@foo.com"</code> is sending a test email.</p>
<p>In the logs of the redash server, when I‚Äôm trying to reset a password (with <code>/forgot</code>), I have the following error:</p>
<pre><code class="lang-auto">[2022-06-17 08:11:52,452][PID:12][ERROR][redash.handlers.authentication] Failed to verify invite token: XXxXxX0XXX, org=None
Traceback (most recent call last):
  File "/app/redash/handlers/authentication.py", line 31, in render_token_login_page
    user_id = validate_token(token)
  File "/app/redash/authentication/account.py", line 41, in validate_token
    return serializer.loads(token, max_age=max_token_age)
  File "/usr/local/lib/python2.7/site-packages/itsdangerous.py", line 643, in loads
    .unsign(s, max_age, return_timestamp=True)
  File "/usr/local/lib/python2.7/site-packages/itsdangerous.py", line 436, in unsign
    raise sig_error
BadSignature: No '.' found in value
</code></pre>
<p>It has been working on the past and I do not remember changing the configuration.<br>
I‚Äôm using a self-host version of Redash 8.0.0+b32245 (a16f551e), using Ubuntu 18.04.</p>
<p>Thank you for your help!</p>
          <p><a href="https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642/1</link>
        <pubDate>Fri, 17 Jun 2022 08:23:05 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10642-1</guid>
        <source url="https://discuss.redash.io/t/unable-to-send-invitation-password-reset-emails/10642.rss">Unable to send invitation/password reset emails</source>
      </item>
  </channel>
</rss>
