<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Why query error 404</title>
    <link>https://discuss.redash.io/t/why-query-error-404/10720</link>
    <description>I have 2 data sources in Bigquery (connected to Redash)
A.XXX-logs
B.XXX-logs-firebase

I always call some tables from B, and it sccesses.
Today, I find the same tables exist in data source A too, so I want to call them from A but it fail.
Why can&#39;t I call them though they exist?

And also, I made some test dataset in A, but I can&#39;t call them too. There is same error...
What conditions do I need to check and improve?

Error massage
Error running query: **b&#39;{\n &quot;error&quot;: {\n &quot;code&quot;: 404,\n &quot;message&quot;: &quot;Not found: Dataset XXX-logs:analytics_16237366 was not found in location asia-northeast1&quot;,\n &quot;errors&quot;: [\n {\n &quot;message&quot;: &quot;Not found: Dataset XXX-logs:analytics_16237366 was not found in location asia-northeast1&quot;,\n &quot;domain&quot;: &quot;global&quot;,\n &quot;reason&quot;: &quot;notFound&quot;\n }\n ],\n &quot;status&quot;: &quot;NOT_FOUND&quot;\n }\n}\n&#39;**</description>
    
    <lastBuildDate>Tue, 05 Jul 2022 12:15:02 +0000</lastBuildDate>
    <category>Uncategorized</category>
    <atom:link href="https://discuss.redash.io/t/why-query-error-404/10720.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Why query error 404</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Did you configure a <strong>Processing Location</strong> in the Reash Data Source Settings for bigquery? The error says there’s no data in asia-northeast-1. Maybe the data you want is housed in another region?</p>
          <p><a href="https://discuss.redash.io/t/why-query-error-404/10720/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/why-query-error-404/10720/2</link>
        <pubDate>Tue, 05 Jul 2022 12:15:02 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10720-2</guid>
        <source url="https://discuss.redash.io/t/why-query-error-404/10720.rss">Why query error 404</source>
      </item>
      <item>
        <title>Why query error 404</title>
        <dc:creator><![CDATA[calicocookie]]></dc:creator>
        <description><![CDATA[
            <p>I have 2 data sources in Bigquery (connected to Redash)<br>
A.XXX-logs<br>
B.XXX-logs-firebase</p>
<p>I always call some tables from B, and it sccesses.<br>
Today, I find the same tables exist in data source A too, so I want to call them from A but it fail.<br>
Why can’t I call them though they exist?</p>
<p>And also, I made some test dataset in A, but I can’t call them too. There is same error…<br>
What conditions do I need to check and improve?</p>
<p>Error massage<br>
Error running query: <strong>b’{\n “error”: {\n “code”: 404,\n “message”: “Not found: Dataset XXX-logs:analytics_16237366 was not found in location asia-northeast1”,\n “errors”: [\n {\n “message”: “Not found: Dataset XXX-logs:analytics_16237366 was not found in location asia-northeast1”,\n “domain”: “global”,\n “reason”: “notFound”\n }\n ],\n “status”: “NOT_FOUND”\n }\n}\n’</strong></p>
          <p><a href="https://discuss.redash.io/t/why-query-error-404/10720/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/why-query-error-404/10720/1</link>
        <pubDate>Tue, 05 Jul 2022 06:41:49 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10720-1</guid>
        <source url="https://discuss.redash.io/t/why-query-error-404/10720.rss">Why query error 404</source>
      </item>
  </channel>
</rss>
