<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Webhook-redash : Caused by SSLError bad handshake: Error &#39;SSL routines&#39;, &#39;tls process server certificate&#39;, &#39;certificate verify failed&#39;</title>
    <link>https://discuss.redash.io/t/webhook-redash-caused-by-sslerror-bad-handshake-error-ssl-routines-tls-process-server-certificate-certificate-verify-failed/11157</link>
    <description>### Getting error in webhook

Traceback (most recent call last):
  File &quot;/app/redash/destinations/webhook.py&quot;, line 50, in notify
    timeout=5.0,
  File &quot;/usr/local/lib/python3.7/site-packages/requests/api.py&quot;, line 116, in post
    return request(&#39;post&#39;, url, data=data, json=json, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/requests/api.py&quot;, line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/requests/sessions.py&quot;, line 533, in request
    resp = self.send(prep, **send_kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/requests/sessions.py&quot;, line 646, in send
    r = adapter.send(request, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/requests/adapters.py&quot;, line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host=&#39;&#39;, port=443): Max retries exceeded with url: /instance/execute/webhook-redash (Caused by SSLError(SSLError(&quot;bad handshake: Error([(&#39;SSL routines&#39;, &#39;tls_process_server_certificate&#39;, &#39;certificate verify failed&#39;)])&quot;)))


* Redash Version: Version: 9.0.0-beta (dev)
* How did you install Redash: docker compose</description>
    
    <lastBuildDate>Wed, 19 Oct 2022 10:58:58 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/webhook-redash-caused-by-sslerror-bad-handshake-error-ssl-routines-tls-process-server-certificate-certificate-verify-failed/11157.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Webhook-redash : Caused by SSLError bad handshake: Error &#39;SSL routines&#39;, &#39;tls process server certificate&#39;, &#39;certificate verify failed&#39;</title>
        <dc:creator><![CDATA[imr]]></dc:creator>
        <description><![CDATA[
            <h3>
<a name="getting-error-in-webhook-1" class="anchor" href="https://discuss.redash.io#getting-error-in-webhook-1"></a>Getting error in webhook</h3>
<p>Traceback (most recent call last):<br>
File “/app/redash/destinations/webhook.py”, line 50, in notify<br>
timeout=5.0,<br>
File “/usr/local/lib/python3.7/site-packages/requests/api.py”, line 116, in post<br>
return request(‘post’, url, data=data, json=json, **kwargs)<br>
File “/usr/local/lib/python3.7/site-packages/requests/api.py”, line 60, in request<br>
return session.request(method=method, url=url, **kwargs)<br>
File “/usr/local/lib/python3.7/site-packages/requests/sessions.py”, line 533, in request<br>
resp = self.send(prep, **send_kwargs)<br>
File “/usr/local/lib/python3.7/site-packages/requests/sessions.py”, line 646, in send<br>
r = adapter.send(request, **kwargs)<br>
File “/usr/local/lib/python3.7/site-packages/requests/adapters.py”, line 514, in send<br>
raise SSLError(e, request=request)<br>
requests.exceptions.SSLError: HTTPSConnectionPool(host=‘’, port=443): Max retries exceeded with url: /instance/execute/webhook-redash (Caused by SSLError(SSLError(“bad handshake: Error([(‘SSL routines’, ‘tls_process_server_certificate’, ‘certificate verify failed’)])”)))</p>
<ul>
<li>Redash Version: Version: 9.0.0-beta (dev)</li>
<li>How did you install Redash: docker compose</li>
</ul>
          <p><a href="https://discuss.redash.io/t/webhook-redash-caused-by-sslerror-bad-handshake-error-ssl-routines-tls-process-server-certificate-certificate-verify-failed/11157/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/webhook-redash-caused-by-sslerror-bad-handshake-error-ssl-routines-tls-process-server-certificate-certificate-verify-failed/11157/1</link>
        <pubDate>Wed, 19 Oct 2022 10:58:58 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11157-1</guid>
        <source url="https://discuss.redash.io/t/webhook-redash-caused-by-sslerror-bad-handshake-error-ssl-routines-tls-process-server-certificate-certificate-verify-failed/11157.rss">Webhook-redash : Caused by SSLError bad handshake: Error &#39;SSL routines&#39;, &#39;tls process server certificate&#39;, &#39;certificate verify failed&#39;</source>
      </item>
  </channel>
</rss>
