<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"/>
<link href="../../css/checklist_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/desktop_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/desktop_theme_2_be4cb2b86ec06123c5e974acd20fd933d14b129d.css" rel="stylesheet"/>
<link href="../../css/discourse-adplugin_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-akismet_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-cakeday_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-chat-integration_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-details_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-footnote_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-lazy-videos_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/discourse-local-dates_d86c892d7cd5311243d31a8f11787f4b0342874d.css" rel="stylesheet"/>
<link href="../../css/color_definitions_base__2_8fd59ae1f286f43b3ff17996df07ea951685249d.css" rel="stylesheet"/>
<link href="../../css/style.css" rel="stylesheet"/>
<title>V4 Beta data selection exception</title></head>
<body>
<div class="navbar">
<div class="logo"><a href="../../page_0.html"><img alt="" src="../../images/logo_redash.png" srcset=""/></a></div>
<div class="navbar-buttons">
<button class="btn btn-signup">Sign Up</button>
<button class="btn btn-login"><i class="fas fa-user"></i> Login</button>
<button class="btn btn-search"><i class="fas fa-search"></i></button>
<div class="navbar-toggle">
<div class="dots"></div>
<div class="dots"></div>
<div class="dots"></div>
</div>
</div>
</div>
<div class="sidebar">
<div class="sidebar-content">
<div class="logo"><a href="../../page_0.html"><img alt="" src="../../images/logo_redash.png" srcset=""/></a></div>
<ul class="sidebar-grid">
<!-- <li><a href="#"><i class="fas fa-list-ul"></i> Topics</a></li> -->
<li><a href="../../page_0.html"><i class="fas fa-layer-group"></i> Topics</a></li>
<li><a href="../../users.html"><i class="fas fa-users"></i> Users</a></li>
<li><a href="../../about.html"><i class="fas fa-info-circle"></i> About</a></li>
<li><a href="../../faq.html"><i class="fas fa-question-circle"></i> FAQ</a></li>
<li><a href="../../groups.html"><i class="fas fa-users"></i> Groups</a></li>
<li><a href="../../badges.html"><i class="fas fa-certificate"></i> Badges</a></li>
</ul>
<h3 style="font-size: 13px;"><a href="#categories"><span>▼</span>Categories</a></h3>
<hr/>
<ul class="sidebar-grid categories">
<li>
<a class="badge-wrapper bullet" href="../../c/support/6.html">
<span class="badge-category-bg" style="background-color: #BF1E2E"></span>
<span class="badge-category clear-badge">
<span class="category-name">Support</span>
</span>
</a>
</li>
<li>
<a class="badge-wrapper bullet" href="../../c/feature-requests/5.html">
<span class="badge-category-bg" style="background-color: #3AB54A"></span>
<span class="badge-category clear-badge">
<span class="category-name">Feature Requests</span>
</span>
</a>
</li>
<li>
<a class="badge-wrapper bullet" href="../../c/uncategorized/1.html">
<span class="badge-category-bg" style="background-color: #AB9364"></span>
<span class="badge-category clear-badge">
<span class="category-name">Uncategorized</span>
</span>
</a>
</li>
<li>
<a class="badge-wrapper bullet" href="../../c/development/7.html">
<span class="badge-category-bg" style="background-color: #8C6238"></span>
<span class="badge-category clear-badge">
<span class="category-name">Development</span>
</span>
</a>
</li>
<li>
<a class="badge-wrapper bullet" href="../../c/tips-tricks-query-examples/11.html">
<span class="badge-category-bg" style="background-color: #652D90"></span>
<span class="badge-category clear-badge" style="white-space: normal;">
<span class="category-name">Tips, Tricks &amp; Query Examples</span>
</span>
</a>
</li>
<li><a href="../../categories.html"><i class="fas fa-list-ul"></i> All categories</a></li>
</ul>
<h3 style="font-size: 13px;"><a href="#tags"><span>▼</span>Tags</a></h3>
<hr/>
<ul class="sidebar-grid tags">
<li><a href="../../tag/query_results.html"><i class="fas fa-tag"></i> query_results</a></li>
<li><a href="../../tag/feature-request.html"><i class="fas fa-tag"></i> feature-request</a></li>
<li><a href="../../tag/parameters.html"><i class="fas fa-tag"></i> parameters</a></li>
<li><a href="../../tag/visualizations.html"><i class="fas fa-tag"></i> visualizations</a></li>
<li><a href="../../tag/alerts.html"><i class="fas fa-tag"></i> alerts</a></li>
<li><a href="../../tags.html"><i class="fas fa-list-ul"></i> All tags</a></li>
</ul>
</div>
<div class="sidebar-footer">
            © 2023 <a href="https://discuss.redash.io/" target="_blank">discuss.redash.io</a>
</div>
</div>
<div class="overlay"></div>
<div class="content">
<div class="global-notice">
<div class="row">
<div class="alert alert-info alert-read-only" id="global-notice-alert-read-only">
<span class="text">This site is in read only mode. Please continue to browse, but replying, likes,
                        and other actions are disabled for now.</span>
</div>
</div>
</div>
<div class="imported_page" id="imported_page">
<div class="wrap" id="main-outlet" role="main">
<div id="topic-title">
<h1>
<a href="/t/v4-beta-data-selection-exception/1551">V4 Beta data selection exception</a>
</h1>
<div class="topic-category" itemscope="" itemtype="http://schema.org/BreadcrumbList">
<span itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
<a class="badge-wrapper bullet" href="../../c/support/6.html" itemprop="item">
<span class="badge-category-bg" style="background-color: #BF1E2E"></span>
<span class="badge-category clear-badge">
<span class="category-name" itemprop="name">Support</span>
</span>
</a>
<meta content="1" itemprop="position"/>
</span>
</div>
</div>
<div itemscope="" itemtype="http://schema.org/DiscussionForumPosting">
<meta content="V4 Beta data selection exception" itemprop="headline"/>
<meta content="Support" itemprop="articleSection"/>
<meta content="" itemprop="keywords"/>
<div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
<meta content="Redash Discourse" itemprop="name"/>
<div itemprop="logo" itemscope="" itemtype="http://schema.org/ImageObject">
<meta content="https://global.discourse-cdn.com/standard17/uploads/redash1/original/1X/c07bc573841e1e4a0013ea3b6fe088a1534228a3.png" itemprop="url"/>
</div>
</div>
<div class="topic-body crawler-post" id="post_1">
<div class="crawler-post-meta">
<span class="creator" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
<a href="../../u/detail/mali.html" itemprop="url"><img alt="" class="avatar" height="48" loading="lazy" src="../../u/avatars/mali_avatar.png" tabindex="-1" width="48"/><span itemprop="name">mali</span></a>
</span>
<link href="https://discuss.redash.io/t/v4-beta-data-selection-exception/1551" itemprop="mainEntityOfPage"/>
<span class="crawler-post-infos">
<time class="post-time" datetime="2018-02-20T09:27:49Z" itemprop="datePublished">
                    February 20, 2018,  9:27am
                  </time>
<meta content="2018-02-20T09:27:49Z" itemprop="dateModified"/>
<span itemprop="position">1</span>
</span>
</div>
<div class="post" itemprop="articleBody">
<p>Hello,</p>
<p>I am currently using version 2 and now installed version 4 beta for testing. I ran a simple select query on presto. query got completed from presto end but  got below exception on redash</p>
<p>Error running query: (psycopg2.IntegrityError) null value in column “data” violates not-null constraint DETAIL: Failing row contains (3, 1, 1, 57171c8ea294c689cdcb612de1cdc636, SELECT * FROM sometable LIMIT 1000000, null, 113.522103071213, 2018-02-20 09:24:01.495115+00).</p>
<p>I can run same query successfully on version 2.</p>
</div>
<div itemprop="interactionStatistic" itemscope="" itemtype="http://schema.org/InteractionCounter">
<meta content="http://schema.org/LikeAction" itemprop="interactionType"/>
<meta content="0" itemprop="userInteractionCount"/>
<span class="post-likes"></span>
</div>
<div itemprop="interactionStatistic" itemscope="" itemtype="http://schema.org/InteractionCounter">
<meta content="http://schema.org/CommentAction" itemprop="interactionType"/>
<meta content="0" itemprop="userInteractionCount"/>
</div>
</div>
<div class="topic-body crawler-post" id="post_2" itemprop="comment" itemscope="" itemtype="http://schema.org/Comment">
<div class="crawler-post-meta">
<span class="creator" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
<a href="../../u/detail/arikfr.html" itemprop="url"><img alt="" class="avatar" height="48" loading="lazy" src="../../u/avatars/arikfr_avatar.png" tabindex="-1" width="48"/><span itemprop="name">arikfr</span></a>
</span>
<link href="https://discuss.redash.io/t/v4-beta-data-selection-exception/1551" itemprop="mainEntityOfPage"/>
<span class="crawler-post-infos">
<time class="post-time" datetime="2018-02-20T11:05:36Z" itemprop="datePublished">
                    February 20, 2018, 11:05am
                  </time>
<meta content="2018-02-20T11:05:36Z" itemprop="dateModified"/>
<span itemprop="position">2</span>
</span>
</div>
<div class="post" itemprop="text">
<p>For some reason it tries to store an invalid object, when running the query.I looked at the Presto query runner and I can’t see a code path where it will try to store <code>None</code> as the data.</p>
<p>But can you verify that you can connect to Presto from the new Redash instance and check the logs for any errors?</p>
</div>
<div itemprop="interactionStatistic" itemscope="" itemtype="http://schema.org/InteractionCounter">
<meta content="http://schema.org/LikeAction" itemprop="interactionType"/>
<meta content="0" itemprop="userInteractionCount"/>
<span class="post-likes"></span>
</div>
<div itemprop="interactionStatistic" itemscope="" itemtype="http://schema.org/InteractionCounter">
<meta content="http://schema.org/CommentAction" itemprop="interactionType"/>
<meta content="1" itemprop="userInteractionCount"/>
</div>
</div>
<div class="topic-body crawler-post" id="post_3" itemprop="comment" itemscope="" itemtype="http://schema.org/Comment">
<div class="crawler-post-meta">
<span class="creator" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
<a href="../../u/detail/mali.html" itemprop="url"><img alt="" class="avatar" height="48" loading="lazy" src="../../u/avatars/mali_avatar.png" tabindex="-1" width="48"/><span itemprop="name">mali</span></a>
</span>
<link href="https://discuss.redash.io/t/v4-beta-data-selection-exception/1551" itemprop="mainEntityOfPage"/>
<span class="crawler-post-infos">
<time class="post-time" datetime="2018-02-20T11:44:16Z" itemprop="datePublished">
                    February 20, 2018, 11:44am
                  </time>
<meta content="2018-02-20T11:44:16Z" itemprop="dateModified"/>
<span itemprop="position">3</span>
</span>
</div>
<div class="post" itemprop="text">
<p>I can connect to presto. I can run my other queries. portion of log file attached.</p>
<blockquote>
<p>Blockquote<br/>
warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))<br/>
[2018-02-20 09:12:30,227][PID:615][WARNING][MainProcess] celery@ip-10-0-8-31 ready.<br/>
[2018-02-20 09:21:08,195][PID:615][ERROR][MainProcess] Task redash.tasks.execute_query[01ac92eb-c5df-409c-af2f-50579fa402cc] raised unexpected: IntegrityError(’(psycopg2.IntegrityError) null value in colu$<br/>
Traceback (most recent call last):<br/>
File “/usr/local/lib/python2.7/dist-packages/celery/app/trace.py”, line 240, in trace_task<br/>
R = retval = fun(*args, **kwargs)<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/worker.py”, line 71, in <strong>call</strong><br/>
return TaskBase.<strong>call</strong>(self, *args, **kwargs)<br/>
File “/usr/local/lib/python2.7/dist-packages/celery/app/trace.py”, line 438, in <strong>protected_call</strong><br/>
return self.run(*args, **kwargs)<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/tasks/queries.py”, line 522, in execute_query<br/>
scheduled_query).run()<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/tasks/queries.py”, line 474, in run<br/>
run_time, utils.utcnow())<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/models.py”, line 764, in store_result<br/>
for q in queries:<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 2796, in <strong>iter</strong><br/>
self.session._autoflush()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 1373, in _autoflush<br/>
util.raise_from_cause(e)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py”, line 202, in raise_from_cause<br/>
reraise(type(exception), exception, tb=exc_tb, cause=cause)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 1363, in _autoflush<br/>
self.flush()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2137, in flush<br/>
self._flush(objects)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2257, in _flush<br/>
transaction.rollback(_capture_exception=True)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py”, line 60, in <strong>exit</strong><br/>
compat.reraise(exc_type, exc_value, exc_tb)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2221, in _flush<br/>
flush_context.execute()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py”, line 389, in execute<br/>
rec.execute(self)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py”, line 548, in execute<br/>
uow<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py”, line 181, in save_obj<br/>
return self.run(*args, **kwargs)<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/tasks/queries.py”, line 522, in execute_query<br/>
scheduled_query).run()<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/tasks/queries.py”, line 474, in run<br/>
run_time, utils.utcnow())<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/models.py”, line 764, in store_result<br/>
for q in queries:<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 2796, in <strong>iter</strong><br/>
self.session._autoflush()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 1373, in _autoflush<br/>
util.raise_from_cause(e)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py”, line 202, in raise_from_cause<br/>
reraise(type(exception), exception, tb=exc_tb, cause=cause)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 1363, in _autoflush<br/>
self.flush()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2137, in flush<br/>
self._flush(objects)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2257, in _flush<br/>
transaction.rollback(_capture_exception=True)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py”, line 60, in <strong>exit</strong><br/>
compat.reraise(exc_type, exc_value, exc_tb)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2221, in _flush<br/>
flush_context.execute()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py”, line 389, in execute<br/>
rec.execute(self)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py”, line 548, in execute<br/>
uow<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py”, line 181, in save_obj<br/>
mapper, table, insert)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py”, line 835, in _emit_insert_statements<br/>
execute(statement, params)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 945, in execute<br/>
return meth(self, multiparams, params)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py”, line 263, in _execute_on_connection<br/>
return connection._execute_clauseelement(self, multiparams, params)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1053, in _execute_clauseelement<br/>
compiled_sql, distilled_params<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1189, in _execute_context<br/>
context)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1393, in _handle_dbapi_exception<br/>
exc_info<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py”, line 202, in raise_from_cause<br/>
reraise(type(exception), exception, tb=exc_tb, cause=cause)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1182, in _execute_context<br/>
context)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py”, line 469, in do_execute<br/>
cursor.execute(statement, parameters)<br/>
IntegrityError: (psycopg2.IntegrityError) null value in column “data” violates not-null constraint<br/>
DETAIL:  Failing row contains (2, 1, 1, 57171c8ea294c689cdcb612de1cdc636, SELECT *<br/>
FROM careem.trip LIMIT 1000000, null, 117.970770835876, 2018-02-20 09:21:08.172867+00).<br/>
[SQL: ‘INSERT INTO query_results (org_id, data_source_id, query_hash, query, data, runtime, retrieved_at) VALUES (%(org_id)s, %(data_source_id)s, %(query_hash)s, %(query)s, %(data)s, %(runtime)s, %(retri$<br/>
[2018-02-20 09:24:01,504][PID:615][ERROR][MainProcess] Task redash.tasks.execute_query[367a140c-7151-4d6a-9796-c14941979815] raised unexpected: IntegrityError(’(psycopg2.IntegrityError) null value in colu$<br/>
Traceback (most recent call last):<br/>
File “/usr/local/lib/python2.7/dist-packages/celery/app/trace.py”, line 240, in trace_task<br/>
R = retval = fun(*args, **kwargs)<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/worker.py”, line 71, in <strong>call</strong><br/>
return TaskBase.<strong>call</strong>(self, *args, **kwargs)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py”, line 835, in _emit_insert_statements<br/>
execute(statement, params)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 945, in execute<br/>
return meth(self, multiparams, params)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py”, line 263, in _execute_on_connection<br/>
return connection._execute_clauseelement(self, multiparams, params)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1053, in _execute_clauseelement<br/>
compiled_sql, distilled_params<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1189, in _execute_context<br/>
context)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1393, in _handle_dbapi_exception<br/>
exc_info<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py”, line 202, in raise_from_cause<br/>
reraise(type(exception), exception, tb=exc_tb, cause=cause)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1182, in _execute_context<br/>
context)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py”, line 469, in do_execute<br/>
cursor.execute(statement, parameters)<br/>
IntegrityError: (psycopg2.IntegrityError) null value in column “data” violates not-null constraint<br/>
DETAIL:  Failing row contains (2, 1, 1, 57171c8ea294c689cdcb612de1cdc636, SELECT *<br/>
FROM careem.trip LIMIT 1000000, null, 117.970770835876, 2018-02-20 09:21:08.172867+00).<br/>
[SQL: ‘INSERT INTO query_results (org_id, data_source_id, query_hash, query, data, runtime, retrieved_at) VALUES (%(org_id)s, %(data_source_id)s, %(query_hash)s, %(query)s, %(data)s, %(runtime)s, %(retri$<br/>
[2018-02-20 09:24:01,504][PID:615][ERROR][MainProcess] Task redash.tasks.execute_query[367a140c-7151-4d6a-9796-c14941979815] raised unexpected: IntegrityError(’(psycopg2.IntegrityError) null value in colu$<br/>
Traceback (most recent call last):<br/>
File “/usr/local/lib/python2.7/dist-packages/celery/app/trace.py”, line 240, in trace_task<br/>
R = retval = fun(*args, **kwargs)<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/worker.py”, line 71, in <strong>call</strong><br/>
return TaskBase.<strong>call</strong>(self, *args, **kwargs)<br/>
File “/usr/local/lib/python2.7/dist-packages/celery/app/trace.py”, line 438, in <strong>protected_call</strong><br/>
return self.run(*args, **kwargs)<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/tasks/queries.py”, line 522, in execute_query<br/>
scheduled_query).run()<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/tasks/queries.py”, line 474, in run<br/>
run_time, utils.utcnow())<br/>
File “/opt/redash/redash.4.0.0-beta.b3690/redash/models.py”, line 764, in store_result<br/>
for q in queries:<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 2796, in <strong>iter</strong><br/>
self.session._autoflush()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 1373, in _autoflush<br/>
util.raise_from_cause(e)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py”, line 202, in raise_from_cause<br/>
reraise(type(exception), exception, tb=exc_tb, cause=cause)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 1363, in _autoflush<br/>
self.flush()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2137, in flush<br/>
self._flush(objects)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2257, in _flush<br/>
transaction.rollback(_capture_exception=True)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py”, line 60, in <strong>exit</strong><br/>
compat.reraise(exc_type, exc_value, exc_tb)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py”, line 2221, in _flush<br/>
flush_context.execute()<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py”, line 389, in execute<br/>
rec.execute(self)<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py”, line 548, in execute<br/>
uow<br/>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py”, line 181, in save_obj</p>
</blockquote>
</div>
<div itemprop="interactionStatistic" itemscope="" itemtype="http://schema.org/InteractionCounter">
<meta content="http://schema.org/LikeAction" itemprop="interactionType"/>
<meta content="0" itemprop="userInteractionCount"/>
<span class="post-likes"></span>
</div>
<div itemprop="interactionStatistic" itemscope="" itemtype="http://schema.org/InteractionCounter">
<meta content="http://schema.org/CommentAction" itemprop="interactionType"/>
<meta content="0" itemprop="userInteractionCount"/>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="overlay" id="modalOverlay" style="display: none;">
<div class="modal-content">
<p>Login or sign up disabled while the site is in read only mode</p>
<hr/>
<button class="btn btn-login">OK</button>
</div>
</div>
<script src="../../js/script.js"></script>
</body>
</html>