<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Trino data source in 10.0.0-beta.b49597</title>
    <link>https://discuss.redash.io/t/trino-data-source-in-10-0-0-beta-b49597/10068</link>
    <description>Hello,

I&#39;m trying to play around with redash and trino locally using docker and after setting them up and running them in docker containers, I get the following error message when trying to create the data source:

Connection Test Failed:

No connection adapters were found for &#39;https:://localhost:8080/v1/statement&#39;
![image|690x483](upload://hvPEc6FaAzK6Erc0vtlfnktbRlm.png)

Any thoughts what might cause the issue above?

Thank you!</description>
    
    <lastBuildDate>Wed, 02 Mar 2022 08:05:00 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/trino-data-source-in-10-0-0-beta-b49597/10068.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Trino data source in 10.0.0-beta.b49597</title>
        <dc:creator><![CDATA[data_fool]]></dc:creator>
        <description><![CDATA[
            <p>Hello,</p>
<p>I’m trying to play around with redash and trino locally using docker and after setting them up and running them in docker containers, I get the following error message when trying to create the data source:</p>
<p>Connection Test Failed:</p>
<p>No connection adapters were found for ‘https:://localhost:8080/v1/statement’<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/7/7abe26b06d7d6e3364f42a214f4e004d24027e38.png" data-download-href="/uploads/short-url/hvPEc6FaAzK6Erc0vtlfnktbRlm.png?dl=1" title="image" rel="noopener nofollow ugc"><img src="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7abe26b06d7d6e3364f42a214f4e004d24027e38_2_690x483.png" alt="image" data-base62-sha1="hvPEc6FaAzK6Erc0vtlfnktbRlm" width="690" height="483" srcset="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7abe26b06d7d6e3364f42a214f4e004d24027e38_2_690x483.png, https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7abe26b06d7d6e3364f42a214f4e004d24027e38_2_1035x724.png 1.5x, https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7abe26b06d7d6e3364f42a214f4e004d24027e38_2_1380x966.png 2x" data-small-upload="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/7/7abe26b06d7d6e3364f42a214f4e004d24027e38_2_10x10.png"></a></div><p></p>
<p>Any thoughts what might cause the issue above?</p>
<p>Thank you!</p>
          <p><a href="https://discuss.redash.io/t/trino-data-source-in-10-0-0-beta-b49597/10068/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/trino-data-source-in-10-0-0-beta-b49597/10068/1</link>
        <pubDate>Wed, 02 Mar 2022 08:05:00 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10068-1</guid>
        <source url="https://discuss.redash.io/t/trino-data-source-in-10-0-0-beta-b49597/10068.rss">Trino data source in 10.0.0-beta.b49597</source>
      </item>
  </channel>
</rss>
