<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</title>
    <link>https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814</link>
    <description>### Issue Summary

After upgrading from v8 to v10, some (but not all) dashboard accesses give a 500 internal server error because &quot;GET /api/dashboards/xxxxx&quot; does not have a ?legacy query and is not treated as slug.

When I access the same URL again, it works with legacy query without any problem. The python error message indicates that the error is because it is treated as an id and not an integer.

```
[26/Jul/2022:03:17:56 +0000] &quot;GET /api/dashboards/w2378_--jk HTTP/1.1&quot; 500 36 &quot;https://xxxxxxx/dashboard/w2378_--jk&quot; &quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36&quot;
[26/Jul/2022:03:17:59 +0000] &quot;GET /api/dashboards/w2378_--jk?legacy HTTP/1.1&quot; 200 3472 &quot;https://xxxxxx/dashboard/w2378_--jk&quot; &quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36&quot;
```
- The log above is in Safari, but it also occurs in Windows+Chrome.
- We do not know why the legacy query is not attached. 

#### What we want to solve
1. do you have any tips for a solution?
2. is there any way to reconfigure an existing slug based dashboard to be id based?

### error msg
```
server_1            | [SQL: SELECT dashboards.updated_at AS dashboards_updated_at, dashboards.created_at AS dashboards_created_at, dashboards.id AS dashboards_id, dashboards.version AS dashboards_version, dashboards.org_id AS dashboards_org_id, dashboards.slug AS dashboards_slug, dashboards.name AS dashboards_name, dashboards.user_id AS dashboards_user_id, dashboards.layout AS dashboards_layout, dashboards.dashboard_filters_enabled AS dashboards_dashboard_filters_enabled, dashboards.is_archived AS dashboards_is_archived, dashboards.is_draft AS dashboards_is_draft, dashboards.tags AS dashboards_tags, dashboards.options AS dashboards_options
server_1            | FROM dashboards
server_1            | WHERE dashboards.id = %(id_1)s AND %(param_1)s = dashboards.org_id]
server_1            | [parameters: {&#39;id_1&#39;: &#39;w2378_--jk&#39;, &#39;param_1&#39;: 1}]
server_1            | (Background on this error at: http://sqlalche.me/e/9h9h)
server_1            | [2022-07-26 03:17:53,035][PID:65][INFO][metrics] method=GET path=/api/dashboards/w2378_--jk endpoint=dashboard status=500 content_type=application/json content_length=36 duration=7.53 query_count=3 query_duration=9.62
server_1            | [2022-07-26 03:17:54,107][PID:57][ERROR][redash.app] Exception on /api/dashboards/w2378_--jk [GET]
server_1            | Traceback (most recent call last):
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1249, in _execute_context
server_1            |     cursor, statement, parameters, context
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py&quot;, line 580, in do_execute
server_1            |     cursor.execute(statement, parameters)
server_1            | psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: &quot;w2378_--jk&quot;
server_1            | LINE 3: WHERE dashboards.id = &#39;w2378_--jk&#39; AND 1 = dash...
server_1            |                               ^
server_1            |
server_1            |
server_1            | The above exception was the direct cause of the following exception:
server_1            |
server_1            | Traceback (most recent call last):
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1949, in full_dispatch_request
server_1            |     rv = self.dispatch_request()
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1935, in dispatch_request
server_1            |     return self.view_functions[rule.endpoint](**req.view_args)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py&quot;, line 458, in wrapper
server_1            |     resp = resource(*args, **kwargs)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/flask_login/utils.py&quot;, line 261, in decorated_view
server_1            |     return func(*args, **kwargs)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/flask/views.py&quot;, line 89, in view
server_1            |     return self.dispatch_request(*args, **kwargs)
server_1            |   File &quot;/app/redash/handlers/base.py&quot;, line 33, in dispatch_request
server_1            |     return super(BaseResource, self).dispatch_request(*args, **kwargs)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py&quot;, line 573, in dispatch_request
server_1            |     resp = meth(*args, **kwargs)
server_1            |   File &quot;/app/redash/permissions.py&quot;, line 71, in decorated
server_1            |     return fn(*args, **kwargs)
server_1            |   File &quot;/app/redash/handlers/dashboards.py&quot;, line 195, in get
server_1            |     dashboard = get_object_or_404(fn, dashboard_id, self.current_org)
server_1            |   File &quot;/app/redash/handlers/base.py&quot;, line 74, in get_object_or_404
server_1            |     rv = fn(*args, **kwargs)
server_1            |   File &quot;/app/redash/models/mixins.py&quot;, line 28, in get_by_id_and_org
server_1            |     return query.one()
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py&quot;, line 3300, in one
server_1            |     ret = self.one_or_none()
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py&quot;, line 3269, in one_or_none
server_1            |     ret = list(self)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py&quot;, line 3342, in __iter__
server_1            |     return self._execute_and_instances(context)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py&quot;, line 3367, in _execute_and_instances
server_1            |     result = conn.execute(querycontext.statement, self._params)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 988, in execute
server_1            |     return meth(self, multiparams, params)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py&quot;, line 287, in _execute_on_connection
server_1            |     return connection._execute_clauseelement(self, multiparams, params)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1107, in _execute_clauseelement
server_1            |     distilled_params,
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1253, in _execute_context
server_1            |     e, statement, parameters, cursor, context
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1473, in _handle_dbapi_exception
server_1            |     util.raise_from_cause(sqlalchemy_exception, exc_info)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py&quot;, line 398, in raise_from_cause
server_1            |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py&quot;, line 152, in reraise
server_1            |     raise value.with_traceback(tb)
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1249, in _execute_context
server_1            |     cursor, statement, parameters, context
server_1            |   File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py&quot;, line 580, in do_execute
server_1            |     cursor.execute(statement, parameters)
server_1            | sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: &quot;w2378_--jk&quot;
server_1            | LINE 3: WHERE dashboards.id = &#39;w2378_--jk&#39; AND 1 = dash...
```

### Codes examined.
I looked at the code below, but I couldn&#39;t figure out how the process is adding a LEGACY query.
https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/client/app/services/dashboard.js#L162
https://github.com/getredash/redash/blob/master/redash/handlers/dashboards.py#L190

### Technical details:
* Redash Version:8.0.0.b32245 -&gt; 10.1.0.b50633
* Browser/OS: Chrome 103 / Windows10
* How did you install Redash: official docker image / Amazon EC2

Thank you.</description>
    
    <lastBuildDate>Tue, 26 Jul 2022 21:13:21 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</title>
        <dc:creator><![CDATA[ishiguro]]></dc:creator>
        <description><![CDATA[
            <blockquote>
<p>Visit the dashboard using the <code>/dashboard</code> endpoint, and update your bookmarks to the version with the integer id included.</p>
</blockquote>
<p>Thank you very much. I will try this way.</p>
          <p><a href="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814/3">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814/3</link>
        <pubDate>Tue, 26 Jul 2022 21:13:21 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10814-3</guid>
        <source url="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814.rss">After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</source>
      </item>
      <item>
        <title>After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Sorry for the confusion. This is expected and is mentioned in the <a href="https://github.com/getredash/redash/releases/tag/v10.0.0">release notes for V10</a>:</p>
<blockquote>
<h2>Dashboard URL Changes</h2>
<p>Dashboard URLs now include the dashboard id and slug.</p>
<p>For example, given a dashboard with the slug <code>account-overview</code> and an id of <code>251</code>:</p>
<p><strong>Before</strong><br>
<code>https://redash.app/dashboards/account-overview</code></p>
<p><strong>After</strong><br>
<code>https://redash.app/dashboards/251-account-overview</code></p>
<p>The dashboard can also be reached using the new <code>/dashboard</code> (notice this is singular) endpoint. It accepts <em>either</em> an ID or a slug:</p>
<ul>
<li><code>https://redash.app/dashboard/251</code></li>
<li><code>https://redash.app/dashboard/account-overview</code></li>
</ul>
<p>Either of these will redirect to the <strong>After</strong> link above. Dashboard ID’s are guaranteed to be unique. But dashboards can share the same slug. If a user visits <code>/dashboard/&lt;some slug&gt;</code> and more than one dashboard exists with that slug, they will be redirected to the earliest created dashboard with that slug.</p>
</blockquote>
<hr>
<blockquote>
<ol>
<li>is there any way to reconfigure an existing slug based dashboard to be id based?</li>
</ol>
</blockquote>
<p>Visit the dashboard using the <code>/dashboard</code> endpoint, and update your bookmarks to the version with the integer id included.</p>
          <p><a href="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814/2</link>
        <pubDate>Tue, 26 Jul 2022 17:01:51 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10814-2</guid>
        <source url="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814.rss">After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</source>
      </item>
      <item>
        <title>After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</title>
        <dc:creator><![CDATA[ishiguro]]></dc:creator>
        <description><![CDATA[
            <h3>
<a name="issue-summary-1" class="anchor" href="https://discuss.redash.io#issue-summary-1"></a>Issue Summary</h3>
<p>After upgrading from v8 to v10, some (but not all) dashboard accesses give a 500 internal server error because “GET /api/dashboards/xxxxx” does not have a ?legacy query and is not treated as slug.</p>
<p>When I access the same URL again, it works with legacy query without any problem. The python error message indicates that the error is because it is treated as an id and not an integer.</p>
<pre><code class="lang-auto">[26/Jul/2022:03:17:56 +0000] "GET /api/dashboards/w2378_--jk HTTP/1.1" 500 36 "https://xxxxxxx/dashboard/w2378_--jk" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
[26/Jul/2022:03:17:59 +0000] "GET /api/dashboards/w2378_--jk?legacy HTTP/1.1" 200 3472 "https://xxxxxx/dashboard/w2378_--jk" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
</code></pre>
<ul>
<li>The log above is in Safari, but it also occurs in Windows+Chrome.</li>
<li>We do not know why the legacy query is not attached.</li>
</ul>
<h4>
<a name="what-we-want-to-solve-2" class="anchor" href="https://discuss.redash.io#what-we-want-to-solve-2"></a>What we want to solve</h4>
<ol>
<li>do you have any tips for a solution?</li>
<li>is there any way to reconfigure an existing slug based dashboard to be id based?</li>
</ol>
<h3>
<a name="error-msg-3" class="anchor" href="https://discuss.redash.io#error-msg-3"></a>error msg</h3>
<pre><code class="lang-auto">server_1            | [SQL: SELECT dashboards.updated_at AS dashboards_updated_at, dashboards.created_at AS dashboards_created_at, dashboards.id AS dashboards_id, dashboards.version AS dashboards_version, dashboards.org_id AS dashboards_org_id, dashboards.slug AS dashboards_slug, dashboards.name AS dashboards_name, dashboards.user_id AS dashboards_user_id, dashboards.layout AS dashboards_layout, dashboards.dashboard_filters_enabled AS dashboards_dashboard_filters_enabled, dashboards.is_archived AS dashboards_is_archived, dashboards.is_draft AS dashboards_is_draft, dashboards.tags AS dashboards_tags, dashboards.options AS dashboards_options
server_1            | FROM dashboards
server_1            | WHERE dashboards.id = %(id_1)s AND %(param_1)s = dashboards.org_id]
server_1            | [parameters: {'id_1': 'w2378_--jk', 'param_1': 1}]
server_1            | (Background on this error at: http://sqlalche.me/e/9h9h)
server_1            | [2022-07-26 03:17:53,035][PID:65][INFO][metrics] method=GET path=/api/dashboards/w2378_--jk endpoint=dashboard status=500 content_type=application/json content_length=36 duration=7.53 query_count=3 query_duration=9.62
server_1            | [2022-07-26 03:17:54,107][PID:57][ERROR][redash.app] Exception on /api/dashboards/w2378_--jk [GET]
server_1            | Traceback (most recent call last):
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
server_1            |     cursor, statement, parameters, context
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
server_1            |     cursor.execute(statement, parameters)
server_1            | psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "w2378_--jk"
server_1            | LINE 3: WHERE dashboards.id = 'w2378_--jk' AND 1 = dash...
server_1            |                               ^
server_1            |
server_1            |
server_1            | The above exception was the direct cause of the following exception:
server_1            |
server_1            | Traceback (most recent call last):
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
server_1            |     rv = self.dispatch_request()
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
server_1            |     return self.view_functions[rule.endpoint](**req.view_args)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
server_1            |     resp = resource(*args, **kwargs)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
server_1            |     return func(*args, **kwargs)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
server_1            |     return self.dispatch_request(*args, **kwargs)
server_1            |   File "/app/redash/handlers/base.py", line 33, in dispatch_request
server_1            |     return super(BaseResource, self).dispatch_request(*args, **kwargs)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
server_1            |     resp = meth(*args, **kwargs)
server_1            |   File "/app/redash/permissions.py", line 71, in decorated
server_1            |     return fn(*args, **kwargs)
server_1            |   File "/app/redash/handlers/dashboards.py", line 195, in get
server_1            |     dashboard = get_object_or_404(fn, dashboard_id, self.current_org)
server_1            |   File "/app/redash/handlers/base.py", line 74, in get_object_or_404
server_1            |     rv = fn(*args, **kwargs)
server_1            |   File "/app/redash/models/mixins.py", line 28, in get_by_id_and_org
server_1            |     return query.one()
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3300, in one
server_1            |     ret = self.one_or_none()
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3269, in one_or_none
server_1            |     ret = list(self)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
server_1            |     return self._execute_and_instances(context)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
server_1            |     result = conn.execute(querycontext.statement, self._params)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
server_1            |     return meth(self, multiparams, params)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
server_1            |     return connection._execute_clauseelement(self, multiparams, params)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
server_1            |     distilled_params,
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
server_1            |     e, statement, parameters, cursor, context
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
server_1            |     util.raise_from_cause(sqlalchemy_exception, exc_info)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
server_1            |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
server_1            |     raise value.with_traceback(tb)
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
server_1            |     cursor, statement, parameters, context
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
server_1            |     cursor.execute(statement, parameters)
server_1            | sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "w2378_--jk"
server_1            | LINE 3: WHERE dashboards.id = 'w2378_--jk' AND 1 = dash...
</code></pre>
<h3>
<a name="codes-examined-4" class="anchor" href="https://discuss.redash.io#codes-examined-4"></a>Codes examined.</h3>
<p>I looked at the code below, but I couldn’t figure out how the process is adding a LEGACY query.</p><aside class="onebox githubblob" data-onebox-src="https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/client/app/services/dashboard.js#L162">
  <header class="source">

      <a href="https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/client/app/services/dashboard.js#L162" target="_blank" rel="noopener nofollow ugc">github.com</a>
  </header>

  <article class="onebox-body">
    <h4><a href="https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/client/app/services/dashboard.js#L162" target="_blank" rel="noopener nofollow ugc">getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/client/app/services/dashboard.js#L162</a></h4>



    <pre class="onebox"><code class="lang-js">
      <ol class="start lines" start="152" style="counter-reset: li-counter 151 ;">
          <li>    data = transformSingle(data);</li>
          <li>  }</li>
          <li>  return data;</li>
          <li>}</li>
          <li>
          </li>
<li>const saveOrCreateUrl = data =&gt; (data.id ? `api/dashboards/${data.id}` : "api/dashboards");</li>
          <li>const DashboardService = {</li>
          <li>  get: ({ id, slug }) =&gt; {</li>
          <li>    const params = {};</li>
          <li>    if (!id) {</li>
          <li class="selected">      params.legacy = null;</li>
          <li>    }</li>
          <li>    return axios.get(`api/dashboards/${id || slug}`, { params }).then(transformResponse);</li>
          <li>  },</li>
          <li>  getByToken: ({ token }) =&gt; axios.get(`api/dashboards/public/${token}`).then(transformResponse),</li>
          <li>  save: data =&gt; axios.post(saveOrCreateUrl(data), data).then(transformResponse),</li>
          <li>  delete: ({ id }) =&gt; axios.delete(`api/dashboards/${id}`).then(transformResponse),</li>
          <li>  query: params =&gt; axios.get("api/dashboards", { params }).then(transformResponse),</li>
          <li>  recent: params =&gt; axios.get("api/dashboards/recent", { params }).then(transformResponse),</li>
          <li>  myDashboards: params =&gt; axios.get("api/dashboards/my", { params }).then(transformResponse),</li>
          <li>  favorites: params =&gt; axios.get("api/dashboards/favorites", { params }).then(transformResponse),</li>
      </ol>
    </code></pre>



  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>
<aside class="onebox githubblob" data-onebox-src="https://github.com/getredash/redash/blob/master/redash/handlers/dashboards.py#L190">
  <header class="source">

      <a href="https://github.com/getredash/redash/blob/master/redash/handlers/dashboards.py#L190" target="_blank" rel="noopener nofollow ugc">github.com</a>
  </header>

  <article class="onebox-body">
    <h4><a href="https://github.com/getredash/redash/blob/master/redash/handlers/dashboards.py#L190" target="_blank" rel="noopener nofollow ugc">getredash/redash/blob/master/redash/handlers/dashboards.py#L190</a></h4>



    <pre class="onebox"><code class="lang-py">
      <ol class="start lines" start="180" style="counter-reset: li-counter 179 ;">
          <li>
          </li>
<li>:&gt;json number widget.id: Widget ID</li>
          <li>:&gt;json number widget.width: Widget size</li>
          <li>:&gt;json object widget.options: Widget options</li>
          <li>:&gt;json number widget.dashboard_id: ID of dashboard containing this widget</li>
          <li>:&gt;json string widget.text: Widget contents, if this is a text-box widget</li>
          <li>:&gt;json object widget.visualization: Widget contents, if this is a visualization widget</li>
          <li>:&gt;json string widget.created_at: ISO format timestamp for widget creation</li>
          <li>:&gt;json string widget.updated_at: ISO format timestamp for last widget modification</li>
          <li>"""</li>
          <li class="selected">if request.args.get("legacy") is not None:</li>
          <li>    fn = models.Dashboard.get_by_slug_and_org</li>
          <li>else:</li>
          <li>    fn = models.Dashboard.get_by_id_and_org</li>
          <li>
          </li>
<li>dashboard = get_object_or_404(fn, dashboard_id, self.current_org)</li>
          <li>response = DashboardSerializer(</li>
          <li>    dashboard, with_widgets=True, user=self.current_user</li>
          <li>).serialize()</li>
          <li>
          </li>
<li>api_key = models.ApiKey.get_by_object(dashboard)</li>
      </ol>
    </code></pre>



  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>

<h3>
<a name="technical-details-5" class="anchor" href="https://discuss.redash.io#technical-details-5"></a>Technical details:</h3>
<ul>
<li>Redash Version:8.0.0.b32245 → 10.1.0.b50633</li>
<li>Browser/OS: Chrome 103 / Windows10</li>
<li>How did you install Redash: official docker image / Amazon EC2</li>
</ul>
<p>Thank you.</p>
          <p><a href="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814/1</link>
        <pubDate>Tue, 26 Jul 2022 06:01:05 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-10814-1</guid>
        <source url="https://discuss.redash.io/t/after-upgrade-access-to-the-dashboard-is-not-accompanied-by-a-legacy-query-resulting-in-a-500-error/10814.rss">After upgrade, access to the dashboard is not accompanied by a legacy query, resulting in a 500 error</source>
      </item>
  </channel>
</rss>
