<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Redash Keycloak SAML Issue - Redash Discourse</title>
    <meta name="description" content="I am getting 500 error while connecting over SAML through keycloak 
  
Here is the logs 
[2023-01-31 05:06:09,175][PID:9][ERROR][redash.app] Exception on /saml/login [GET] 
server_1            | Traceback (most recent ca&amp;hellip;">
    <meta name="generator" content="Discourse 3.2.0.beta2-dev - https://github.com/discourse/discourse version 83621ccbe797223b48b624b00ef04f24672e1f03">
<link rel="icon" type="image/png" href="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/1X/01e20869afc0877e3e5aee0f94419b9e9bffa961_2_32x32.ico">
<link rel="apple-touch-icon" type="image/png" href="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/1X/e1838a8a0c506503a22e0c60e2334374b2895c87_2_180x180.png">
<meta name="theme-color" media="all" content="#ffffff">

<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes, viewport-fit=cover">
<link rel="canonical" href="https://discuss.redash.io/t/redash-keycloak-saml-issue/11527" />

<link rel="search" type="application/opensearchdescription+xml" href="https://discuss.redash.io/opensearch.xml" title="Redash Discourse Search">

    <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/color_definitions_base__2_8fd59ae1f286f43b3ff17996df07ea951685249d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" class="light-scheme"/>

  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/desktop_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="desktop"  />



  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/checklist_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="checklist"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-adplugin_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-adplugin"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-akismet_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-akismet"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-cakeday_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-cakeday"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-chat-integration_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-chat-integration"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-details_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-details"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-footnote_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-footnote"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-lazy-videos_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-lazy-videos"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-local-dates_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-local-dates"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-narrative-bot_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-narrative-bot"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-presence_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-presence"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-solved_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-solved"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/discourse-spoiler-alert_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="discourse-spoiler-alert"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/hosted-site_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="hosted-site"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/poll_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="poll"  />
  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/poll_desktop_d86c892d7cd5311243d31a8f11787f4b0342874d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="poll_desktop"  />

  <link href="https://sjc6.discourse-cdn.com/standard17/stylesheets/desktop_theme_2_be4cb2b86ec06123c5e974acd20fd933d14b129d.css?__ws=discuss.redash.io" media="all" rel="stylesheet" data-target="desktop_theme" data-theme-id="2" data-theme-name="default"/>

    
    <meta id="data-ga-universal-analytics" data-tracking-code="UA-47088186-6" data-json="{&quot;cookieDomain&quot;:&quot;auto&quot;}" data-auto-link-domains="">

  <link rel="preload" href="https://global.discourse-cdn.com/standard17/assets/google-universal-analytics-v3-08add7ec997ab472fcd9f821d32ff7caf4b8b9a5de2ec18ca723a040be07a098.gz.js" as="script">
<script defer src="https://global.discourse-cdn.com/standard17/assets/google-universal-analytics-v3-08add7ec997ab472fcd9f821d32ff7caf4b8b9a5de2ec18ca723a040be07a098.gz.js"></script>


        <link rel="alternate nofollow" type="application/rss+xml" title="RSS feed of &#39;Redash Keycloak SAML Issue&#39;" href="https://discuss.redash.io/t/redash-keycloak-saml-issue/11527.rss" />
    <meta property="og:site_name" content="Redash Discourse" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:image" content="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4_2_1024x576.jpeg" />
<meta property="og:image" content="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4_2_1024x576.jpeg" />
<meta property="og:url" content="https://discuss.redash.io/t/redash-keycloak-saml-issue/11527" />
<meta name="twitter:url" content="https://discuss.redash.io/t/redash-keycloak-saml-issue/11527" />
<meta property="og:title" content="Redash Keycloak SAML Issue" />
<meta name="twitter:title" content="Redash Keycloak SAML Issue" />
<meta property="og:description" content="I am getting 500 error while connecting over SAML through keycloak     Here is the logs  [2023-01-31 05:06:09,175][PID:9][ERROR][redash.app] Exception on /saml/login [GET]  server_1            | Traceback (most recent call last):  server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connection.py”, line 159, in _new_conn  server_1            |     (self._dns_host, self.port), self.timeout, **extra_kw)  server_1            |   File “/usr/local/lib/python3.7/site-packages/u..." />
<meta name="twitter:description" content="I am getting 500 error while connecting over SAML through keycloak     Here is the logs  [2023-01-31 05:06:09,175][PID:9][ERROR][redash.app] Exception on /saml/login [GET]  server_1            | Traceback (most recent call last):  server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connection.py”, line 159, in _new_conn  server_1            |     (self._dns_host, self.port), self.timeout, **extra_kw)  server_1            |   File “/usr/local/lib/python3.7/site-packages/u..." />
<meta property="article:published_time" content="2023-01-31T05:14:26+00:00" />
<meta property="og:ignore_canonical" content="true" />


    
  </head>
  <body class="crawler ">
    
    <header>
  <a href="/">
    Redash Discourse
  </a>
</header>

    <div id="main-outlet" class="wrap" role="main">
        <div id="topic-title">
    <h1>
      <a href="/t/redash-keycloak-saml-issue/11527">Redash Keycloak SAML Issue</a>
    </h1>


  </div>

  

    <div itemscope itemtype='http://schema.org/DiscussionForumPosting'>
      <meta itemprop='headline' content='Redash Keycloak SAML Issue'>
        <meta itemprop='articleSection' content='Uncategorized'>
      <meta itemprop='keywords' content=''>
      <div itemprop='publisher' itemscope itemtype="http://schema.org/Organization">
        <meta itemprop='name' content='Redash Discourse'>
          <div itemprop='logo' itemscope itemtype="http://schema.org/ImageObject">
            <meta itemprop='url' content='https://global.discourse-cdn.com/standard17/uploads/redash1/original/1X/c07bc573841e1e4a0013ea3b6fe088a1534228a3.png'>
          </div>
      </div>

          <div id='post_1'  class='topic-body crawler-post'>
            <div class='crawler-post-meta'>
              <span class="creator" itemprop="author" itemscope itemtype="http://schema.org/Person">
                <a itemprop="url" href='https://discuss.redash.io/u/smartysam9821'><span itemprop='name'>smartysam9821</span></a>
                
              </span>

              <link itemprop="mainEntityOfPage" href="https://discuss.redash.io/t/redash-keycloak-saml-issue/11527">

                <link itemprop="image" href="https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4.jpeg">

              <span class="crawler-post-infos">
                  <time itemprop='datePublished' datetime='2023-01-31T05:14:26Z' class='post-time'>
                    January 31, 2023,  5:14am
                  </time>
                  <meta itemprop='dateModified' content='2023-01-31T05:14:26Z'>
              <span itemprop='position'>1</span>
              </span>
            </div>
            <div class='post' itemprop='articleBody'>
              <p><strong>I am getting 500 error while connecting over SAML through keycloak</strong></p>
<p><div class="lightbox-wrapper"><a class="lightbox" href="https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4.jpeg" data-download-href="/uploads/short-url/65gJxr3A8CafkbCLOIjhEkeYgPa.jpeg?dl=1" title="redash-keycloak-issue" rel="noopener nofollow ugc"><img src="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4_2_690x388.jpeg" alt="redash-keycloak-issue" data-base62-sha1="65gJxr3A8CafkbCLOIjhEkeYgPa" width="690" height="388" srcset="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4_2_690x388.jpeg, https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4_2_1035x582.jpeg 1.5x, https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/2/2aa58bc9008dbf939412d25ff6ecf06ccc0dc9a4.jpeg 2x" data-dominant-color="FCFBF7"><div class="meta">
<svg class="fa d-icon d-icon-far-image svg-icon" aria-hidden="true"><use href="#far-image"></use></svg><span class="filename">redash-keycloak-issue</span><span class="informations">1222×688 30.1 KB</span><svg class="fa d-icon d-icon-discourse-expand svg-icon" aria-hidden="true"><use href="#discourse-expand"></use></svg>
</div></a></div></p>
<p>Here is the logs<br>
[2023-01-31 05:06:09,175][PID:9][ERROR][redash.app] Exception on /saml/login [GET]<br>
server_1            | Traceback (most recent call last):<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connection.py”, line 159, in _new_conn<br>
server_1            |     (self._dns_host, self.port), self.timeout, **extra_kw)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py”, line 80, in create_connection<br>
server_1            |     raise err<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py”, line 70, in create_connection<br>
server_1            |     sock.connect(sa)<br>
server_1            | ConnectionRefusedError: [Errno 111] Connection refused<br>
server_1            |<br>
server_1            | During handling of the above exception, another exception occurred:<br>
server_1            |<br>
server_1            | Traceback (most recent call last):<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py”, line 600, in urlopen<br>
server_1            |     chunked=chunked)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py”, line 343, in _make_request<br>
server_1            |     self._validate_conn(conn)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py”, line 839, in _validate_conn<br>
server_1            |     conn.connect()<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connection.py”, line 301, in connect<br>
server_1            |     conn = self._new_conn()<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connection.py”, line 168, in _new_conn<br>
server_1            |     self, “Failed to establish a new connection: %s” % e)<br>
server_1            | urllib3.exceptions.NewConnectionError: &lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f46990c3390&gt;: Failed to establish a new connection: [Errno 111] Connection refused<br>
server_1            |<br>
server_1            | During handling of the above exception, another exception occurred:<br>
server_1            |<br>
server_1            | Traceback (most recent call last):<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/requests/adapters.py”, line 449, in send<br>
server_1            |     timeout=timeout<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py”, line 638, in urlopen<br>
server_1            |     _stacktrace=sys.exc_info()[2])<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py”, line 399, in increment<br>
server_1            |     raise MaxRetryError(_pool, url, error or ResponseError(cause))<br>
server_1            | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=‘172.177.61.191’, port=8443): Max retries exceeded with url: /realms/master/protocol/saml/descriptor (Caused by NewConnectionError(‘&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f46990c3390&gt;: Failed to establish a new connection: [Errno 111] Connection refused’))<br>
server_1            |<br>
server_1            | During handling of the above exception, another exception occurred:<br>
server_1            |<br>
server_1            | Traceback (most recent call last):<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/httpbase.py”, line 243, in send<br>
server_1            |     r = requests.request(method, url, **_kwargs)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/requests/api.py”, line 60, in request<br>
server_1            |     return session.request(method=method, url=url, **kwargs)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/requests/sessions.py”, line 533, in request<br>
server_1            |     resp = self.send(prep, **send_kwargs)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/requests/sessions.py”, line 646, in send<br>
server_1            |     r = adapter.send(request, **kwargs)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/requests/adapters.py”, line 516, in send<br>
server_1            |     raise ConnectionError(e, request=request)<br>
server_1            | requests.exceptions.ConnectionError: HTTPSConnectionPool(host=‘172.177.61.191’, port=8443): Max retries exceeded with url: /realms/master/protocol/saml/descriptor (Caused by NewConnectionError(‘&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f46990c3390&gt;: Failed to establish a new connection: [Errno 111] Connection refused’))<br>
server_1            |<br>
server_1            | During handling of the above exception, another exception occurred:<br>
server_1            |<br>
server_1            | Traceback (most recent call last):<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask/app.py”, line 2446, in wsgi_app<br>
server_1            |     response = self.full_dispatch_request()<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask/app.py”, line 1951, in full_dispatch_request<br>
server_1            |     rv = self.handle_user_exception(e)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask_restful/<strong>init</strong>.py”, line 269, in error_router<br>
server_1            |     return original_handler(e)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask/app.py”, line 1820, in handle_user_exception<br>
server_1            |     reraise(exc_type, exc_value, tb)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask/_compat.py”, line 39, in reraise<br>
server_1            |     raise value<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask/app.py”, line 1949, in full_dispatch_request<br>
server_1            |     rv = self.dispatch_request()<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/flask/app.py”, line 1935, in dispatch_request<br>
server_1            |     return self.view_functions<a>rule.endpoint</a><br>
server_1            |   File “/app/redash/authentication/saml_auth.py”, line 145, in sp_initiated<br>
server_1            |     saml_client = get_saml_client(current_org)<br>
server_1            |   File “/app/redash/authentication/saml_auth.py”, line 92, in get_saml_client<br>
server_1            |     sp_config.load(saml_settings)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/config.py”, line 382, in load<br>
server_1            |     self.load_complex(cnf, metadata_construction=metadata_construction)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/config.py”, line 316, in load_complex<br>
server_1            |     self.load_metadata(cnf[“metadata”]))<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/config.py”, line 425, in load_metadata<br>
server_1            |     mds.imp(metadata_conf)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/mdstore.py”, line 1021, in imp<br>
server_1            |     self.load(key, **val)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/mdstore.py”, line 1009, in load<br>
server_1            |     _md.load()<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/mdstore.py”, line 790, in load<br>
server_1            |     response = self.http.send(self.url)<br>
server_1            |   File “/usr/local/lib/python3.7/site-packages/saml2/httpbase.py”, line 246, in send<br>
server_1            |     raise ConnectionError(“%s” % exc)<br>
server_1            | saml2.httpbase.ConnectionError: HTTPSConnectionPool(host=‘172.177.61.191’, port=8443): Max retries exceeded with url: /realms/master/protocol/saml/descriptor (Caused by NewConnectionError(‘&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f46990c3390&gt;: Failed to establish a new connection: [Errno 111] Connection refused’))<br>
server_1            | [2023-01-31 05:06:09,178][PID:9][INFO][metrics] method=GET path=/saml/login endpoint=saml_auth_sp_initiated status=500 content_type=text/html content_length=290 duration=10.97 query_count=1 query_duration=0.92<br>
server_1            | [2023-01-31 05:06:09,179][PID:9][INFO][metrics] method=GET path=/saml/login endpoint=saml_auth_sp_initiated status=500 content_type=? content_length=-1 duration=12.27 query_count=1 query_duration=0.92<br>
server_1            | [2023-01-31 05:06:09,447][PID:12][INFO][metrics] method=GET path=/favicon.ico endpoint=redash_index status=302 content_type=text/html; charset=utf-8 content_length=369 duration=0.40 query_count=0 query_duration=0.00<br>
server_1            | [2023-01-31 05:06:09,875][PID:11][INFO][metrics] method=GET path=/login endpoint=redash_login status=200 content_type=text/html; charset=utf-8 content_length=2174 duration=16.92 query_count=1 query_duration=0.89<br>
azureuser@redash:~$</p>
            </div>

            <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
              <meta itemprop="interactionType" content="http://schema.org/LikeAction"/>
              <meta itemprop="userInteractionCount" content="0" />
              <span class='post-likes'></span>
            </div>

            <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
                <meta itemprop="interactionType" content="http://schema.org/CommentAction"/>
                <meta itemprop="userInteractionCount" content="0" />
              </div>

          </div>
    </div>






    </div>
    <footer class="container wrap">
  <nav class='crawler-nav'>
    <ul>
      <li itemscope itemtype='http://schema.org/SiteNavigationElement'>
        <span itemprop='name'>
          <a href='/' itemprop="url">Home </a>
        </span>
      </li>
      <li itemscope itemtype='http://schema.org/SiteNavigationElement'>
        <span itemprop='name'>
          <a href='/categories' itemprop="url">Categories </a>
        </span>
      </li>
      <li itemscope itemtype='http://schema.org/SiteNavigationElement'>
        <span itemprop='name'>
          <a href='/guidelines' itemprop="url">FAQ/Guidelines </a>
        </span>
      </li>
        <li itemscope itemtype='http://schema.org/SiteNavigationElement'>
          <span itemprop='name'>
            <a href='http://redash.io/terms.html' itemprop="url">Terms of Service </a>
          </span>
        </li>
        <li itemscope itemtype='http://schema.org/SiteNavigationElement'>
          <span itemprop='name'>
            <a href='http://redash.io/privacy.html' itemprop="url">Privacy Policy </a>
          </span>
        </li>
    </ul>
  </nav>
  <p class='powered-by-link'>Powered by <a href="https://www.discourse.org">Discourse</a>, best viewed with JavaScript enabled</p>
</footer>

    
    
  </body>
  
</html>
