<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>[Redash - Azure AD App - Cognito] SAML Setup Failing</title>
    <link>https://discuss.redash.io/t/redash-azure-ad-app-cognito-saml-setup-failing/9954</link>
    <description>I have a Cognito User Pool in AWS dedicated to Redash, also have Microsoft AD App in Azure connected to AWS Redash. I am trying to connect Redash with the SAML Authentication Enabled to Microsoft AD App. But for some reason, there is a missing mapper, and AD to Redash mapping is not getting successful.

So, I am trying to make a connectivity like Redash SSO -&gt; Microsoft AD App -&gt; AWS Cognito User Pool, and trying to on-board users in AD to Redash

Redash Image(Running in Kubernetes): redash/redash:8.0.2.b37747

**SAML Configuration in the Redash UI**
SAML Metadata URL: https://login.microsoftonline.com/yyyyyyy-yyyyyy-yyyyyy-yyyyyy/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxx-xxxxxx-xxxxxx-xxxxxxx
SAML Entity ID: urn:amazon:cognito:sp:&lt;cognito_ARN&gt;
SAML NameID Format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress

**Logs of the Redash Pod running in the AWS EKS**
```
[2022-02-01 14:23:49,651] ERROR in app: Exception on /saml/callback [POST]
Traceback (most recent call last):
File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1982, in wsgi_app
response = self.full_dispatch_request()
File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File &quot;/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py&quot;, line 271, in error_router
return original_handler(e)
File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1612, in full_dispatch_request
rv = self.dispatch_request()
File &quot;/usr/local/lib/python2.7/site-packages/flask/app.py&quot;, line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File &quot;/app/redash/authentication/saml_auth.py&quot;, line 82, in idp_initiated
name = &quot;%s %s&quot; % (authn_response.ava[&#39;FirstName&#39;][0], authn_response.ava[&#39;LastName&#39;][0])
KeyError: &#39;FirstName&#39;
```
Have gone through couple of issues already raised in this forum regarding the same but still no luck!

I&#39;d highly appreciate if someone can help me get this fixed, thanks in advance!</description>
    
    <lastBuildDate>Thu, 03 Feb 2022 06:10:49 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/redash-azure-ad-app-cognito-saml-setup-failing/9954.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>[Redash - Azure AD App - Cognito] SAML Setup Failing</title>
        <dc:creator><![CDATA[sankalp7654]]></dc:creator>
        <description><![CDATA[
            <p>I have a Cognito User Pool in AWS dedicated to Redash, also have Microsoft AD App in Azure connected to AWS Redash. I am trying to connect Redash with the SAML Authentication Enabled to Microsoft AD App. But for some reason, there is a missing mapper, and AD to Redash mapping is not getting successful.</p>
<p>So, I am trying to make a connectivity like Redash SSO → Microsoft AD App → AWS Cognito User Pool, and trying to on-board users in AD to Redash</p>
<p>Redash Image(Running in Kubernetes): redash/redash:8.0.2.b37747</p>
<p><strong>SAML Configuration in the Redash UI</strong><br>
SAML Metadata URL: <a href="https://login.microsoftonline.com/yyyyyyy-yyyyyy-yyyyyy-yyyyyy/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxx-xxxxxx-xxxxxx-xxxxxxx" rel="noopener nofollow ugc">https://login.microsoftonline.com/yyyyyyy-yyyyyy-yyyyyy-yyyyyy/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxx-xxxxxx-xxxxxx-xxxxxxx</a><br>
SAML Entity ID: urn:amazon:cognito:sp:&lt;cognito_ARN&gt;<br>
SAML NameID Format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</p>
<p><strong>Logs of the Redash Pod running in the AWS EKS</strong></p>
<pre><code class="lang-auto">[2022-02-01 14:23:49,651] ERROR in app: Exception on /saml/callback [POST]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
return original_handler(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/redash/authentication/saml_auth.py", line 82, in idp_initiated
name = "%s %s" % (authn_response.ava['FirstName'][0], authn_response.ava['LastName'][0])
KeyError: 'FirstName'
</code></pre>
<p>Have gone through couple of issues already raised in this forum regarding the same but still no luck!</p>
<p>I’d highly appreciate if someone can help me get this fixed, thanks in advance!</p>
          <p><a href="https://discuss.redash.io/t/redash-azure-ad-app-cognito-saml-setup-failing/9954/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redash-azure-ad-app-cognito-saml-setup-failing/9954/1</link>
        <pubDate>Thu, 03 Feb 2022 06:07:01 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9954-1</guid>
        <source url="https://discuss.redash.io/t/redash-azure-ad-app-cognito-saml-setup-failing/9954.rss">[Redash - Azure AD App - Cognito] SAML Setup Failing</source>
      </item>
  </channel>
</rss>
