<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Docker installation problem</title>
    <link>https://discuss.redash.io/t/docker-installation-problem/11190</link>
    <description>Hello everyone,
I&#39;m following the docker installation [guide](https://redash.io/help/open-source/dev-guide/docker) and when I run the `docker-compose run --rm server create_db` it list the following error

```
Traceback (most recent call last):
  File &quot;/app/manage.py&quot;, line 9, in &lt;module&gt;
    manager()
  File &quot;/usr/local/lib/python3.7/site-packages/click/core.py&quot;, line 722, in __call__
    return self.main(*args, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/cli.py&quot;, line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/click/core.py&quot;, line 697, in main
    rv = self.invoke(ctx)
  File &quot;/usr/local/lib/python3.7/site-packages/click/core.py&quot;, line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File &quot;/usr/local/lib/python3.7/site-packages/click/core.py&quot;, line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File &quot;/usr/local/lib/python3.7/site-packages/click/core.py&quot;, line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File &quot;/usr/local/lib/python3.7/site-packages/click/core.py&quot;, line 535, in invoke
    return callback(*args, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/click/decorators.py&quot;, line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/cli.py&quot;, line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File &quot;/usr/local/lib/python3.7/site-packages/flask/cli.py&quot;, line 381, in load_app
    app = call_factory(self, self.create_app)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/cli.py&quot;, line 117, in call_factory
    return app_factory(script_info)
  File &quot;/app/redash/cli/__init__.py&quot;, line 13, in create
    app = current_app or create_app()
  File &quot;/app/redash/app.py&quot;, line 57, in create_app
    extensions.init_app(app)
  File &quot;/app/redash/extensions.py&quot;, line 107, in init_app
    load_extensions(app)
  File &quot;/app/redash/extensions.py&quot;, line 69, in load_extensions
    entry_point_loader(&quot;redash.extensions&quot;, extensions, logger=app.logger, app=app)
  File &quot;/app/redash/extensions.py&quot;, line 30, in entry_point_loader
    for entry_point in entry_points().get(group_name, []):
AttributeError: &#39;EntryPoints&#39; object has no attribute &#39;get&#39;
```

from what I read, the issue lies in `importlib-metadata` which is requirements_bundles.txt file. I have changed it to be a version less than (5). Unfortunatly, it didn&#39;t work.

Any ideas ?</description>
    
    <lastBuildDate>Tue, 08 Nov 2022 18:03:09 +0000</lastBuildDate>
    <category>Support</category>
    <atom:link href="https://discuss.redash.io/t/docker-installation-problem/11190.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Docker installation problem</title>
        <dc:creator><![CDATA[eradman]]></dc:creator>
        <description><![CDATA[
            <p>I started a PR to pin importlib-metadata to 4.13.0</p><aside class="onebox githubpullrequest" data-onebox-src="https://github.com/getredash/redash/pull/5851">
  <header class="source">

      <a href="https://github.com/getredash/redash/pull/5851" target="_blank" rel="noopener nofollow ugc">github.com/getredash/redash</a>
  </header>

  <article class="onebox-body">
    <div class="github-row">



    <div class="github-icon-container" title="Pull Request">
      <svg width="60" height="60" class="github-icon" viewBox="0 0 12 16" aria-hidden="true"><path fill-rule="evenodd" d="M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z"></path></svg>
    </div>

  <div class="github-info-container">



      <h4>
        <a href="https://github.com/getredash/redash/pull/5851" target="_blank" rel="noopener nofollow ugc">Pin importlib-metadata to 4.13.0</a>
      </h4>

    <div class="branches">
      <code>getredash:master</code> ← <code>eradman:build</code>
    </div>

      <div class="github-info">
        <div class="date">
          opened <span class="discourse-local-date" data-format="ll" data-date="2022-11-08" data-time="17:12:25" data-timezone="UTC">05:12PM - 08 Nov 22 UTC</span>
        </div>

        <div class="user">
          <a href="https://github.com/eradman" target="_blank" rel="noopener nofollow ugc">
            <img alt="eradman" src="https://avatars.githubusercontent.com/u/1175398?v=4" class="onebox-avatar-inline" width="20" height="20">
            eradman
          </a>
        </div>

        <div class="lines" title="1 commits changed 1 files with 1 additions and 1 deletions">
          <a href="https://github.com/getredash/redash/pull/5851/files" target="_blank" rel="noopener nofollow ugc">
            <span class="added">+1</span>
            <span class="removed">-1</span>
          </a>
        </div>
      </div>
  </div>
</div>

  <div class="github-row">
    <p class="github-body-container">## What type of PR is this? 

- [x] Bug Fix

## Description

importlib-met<span class="show-more-container"><a href="https://github.com/getredash/redash/pull/5851" target="_blank" rel="noopener nofollow ugc" class="show-more">…</a></span><span class="excerpt hidden">adata-5.0.0 removed SelectableGroups which Redash 10 depends on

See https://github.com/python/importlib_metadata/issues/409

## How is this tested?

- [x] Manually

```
docker-compose run --rm server create_db
```

## Related Tickets &amp; Documents

Solves https://discuss.redash.io/t/docker-installation-problem/11190</span></p>
  </div>

  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>

          <p><a href="https://discuss.redash.io/t/docker-installation-problem/11190/4">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/docker-installation-problem/11190/4</link>
        <pubDate>Tue, 08 Nov 2022 18:03:09 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11190-4</guid>
        <source url="https://discuss.redash.io/t/docker-installation-problem/11190.rss">Docker installation problem</source>
      </item>
      <item>
        <title>Docker installation problem</title>
        <dc:creator><![CDATA[saketbairoliya2]]></dc:creator>
        <description><![CDATA[
            <p>I found this link useful, incase anyone needs: <a href="https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean" class="inline-onebox" rel="noopener nofollow ugc">python - 'EntryPoints' object has no attribute 'get' - Digital ocean - Stack Overflow</a></p>
          <p><a href="https://discuss.redash.io/t/docker-installation-problem/11190/3">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/docker-installation-problem/11190/3</link>
        <pubDate>Sat, 05 Nov 2022 08:53:57 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11190-3</guid>
        <source url="https://discuss.redash.io/t/docker-installation-problem/11190.rss">Docker installation problem</source>
      </item>
      <item>
        <title>Docker installation problem</title>
        <dc:creator><![CDATA[saketbairoliya2]]></dc:creator>
        <description><![CDATA[
            <p>Were you able to get this fixed? I’m also facing the same issue when trying to set this up on M1 Mac.</p>
          <p><a href="https://discuss.redash.io/t/docker-installation-problem/11190/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/docker-installation-problem/11190/2</link>
        <pubDate>Sat, 05 Nov 2022 08:36:43 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11190-2</guid>
        <source url="https://discuss.redash.io/t/docker-installation-problem/11190.rss">Docker installation problem</source>
      </item>
      <item>
        <title>Docker installation problem</title>
        <dc:creator><![CDATA[cla22ire]]></dc:creator>
        <description><![CDATA[
            <p>Hello everyone,<br>
I’m following the docker installation <a href="https://redash.io/help/open-source/dev-guide/docker" rel="noopener nofollow ugc">guide</a> and when I run the <code>docker-compose run --rm server create_db</code> it list the following error</p>
<pre><code class="lang-auto">Traceback (most recent call last):
  File "/app/manage.py", line 9, in &lt;module&gt;
    manager()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 381, in load_app
    app = call_factory(self, self.create_app)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 117, in call_factory
    return app_factory(script_info)
  File "/app/redash/cli/__init__.py", line 13, in create
    app = current_app or create_app()
  File "/app/redash/app.py", line 57, in create_app
    extensions.init_app(app)
  File "/app/redash/extensions.py", line 107, in init_app
    load_extensions(app)
  File "/app/redash/extensions.py", line 69, in load_extensions
    entry_point_loader("redash.extensions", extensions, logger=app.logger, app=app)
  File "/app/redash/extensions.py", line 30, in entry_point_loader
    for entry_point in entry_points().get(group_name, []):
AttributeError: 'EntryPoints' object has no attribute 'get'
</code></pre>
<p>from what I read, the issue lies in <code>importlib-metadata</code> which is requirements_bundles.txt file. I have changed it to be a version less than (5). Unfortunatly, it didn’t work.</p>
<p>Any ideas ?</p>
          <p><a href="https://discuss.redash.io/t/docker-installation-problem/11190/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/docker-installation-problem/11190/1</link>
        <pubDate>Mon, 24 Oct 2022 12:51:46 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11190-1</guid>
        <source url="https://discuss.redash.io/t/docker-installation-problem/11190.rss">Docker installation problem</source>
      </item>
  </channel>
</rss>
